CREATE TABLE IF NOT EXISTS Address (
    Id int not null AUTO_INCREMENT primary key ,
    Country varchar(100),
    City varchar(100),
    County varchar(100),
    StreetAddress varchar(100)
);

ALTER TABLE Location
    DROP COLUMN ADDRESSCITY, ADDRESSCOUNTRY, ADDRESSCOUNTY, ADDRESSSTREETADDRESS;

ALTER TABLE "ORDER"
    DROP COLUMN ADDRESSSTREETADDRESS, ADDRESSCOUNTY, ADDRESSCOUNTRY, ADDRESSCITY;

ALTER TABLE LOCATION
    ADD COLUMN AddressId int;

ALTER TABLE "ORDER"
    ADD COLUMN AddressId int;

ALTER TABLE LOCATION
    ADD FOREIGN KEY (AddressId) REFERENCES Address(Id);

ALTER TABLE "ORDER"
    ADD FOREIGN KEY (AddressId) REFERENCES Address(Id);